### ISSUE TITLE
Option to ignore directories

### ISSUE THREAD

**Issue by Xavientois** [sighol/tree-rs#8]
Would it be possible to add a way to ignore certain files/directories (like the -I option in the unix `tree`)?

**Comment by raw-bin** [comment]
It would also be useful to have the opposite like in the UNIX `tree` tool: `-d` to show _only_ directories.

**Comment by ByteBaker** [comment]
I could code this. @sighol is the aim to be an exact replica of the `tree` command or we can add features as well?

**Comment by sighol** [comment]
@ByteBaker feel free to make a PR with either `-d` or `-I`!

New features are also welcome unless they conflict with an already defined parameter in `tree`.

**Comment by ByteBaker** [comment]
Great! One more thing, I'd also like to upgrade any crate(s) and maybe change some code that isn't idiomatic. Perhaps add some documentation as well.

Should I do it all in one PR or more?

**Comment by sighol** [comment]
Multiple PRs might be better, but that is up to you. As long as it is not one huge commit, then it's good 👍

**Comment by ByteBaker** [comment]
Hi @sighol, I've created #15 with some cleanup. It was a low-hanging fruit so I picked it first. Please review.

I'll start work on `-I` and `-d` soon.

**Comment by ByteBaker** [comment]
@sighol I had made a mistake of linking #16 with this, only to realize it yesterday. But now that #24 is done, things are back in order.
